
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xesjdlfeydgtyhlxciyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhlc2pkbGZleWRndHlobHhjaXlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MDI2NTYsImV4cCI6MjA2MDQ3ODY1Nn0.1Nu1DmPlboAlbZOnnpduLBicx0yik5LhXOrrnvOKQs0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
